### ISSUE TITLE
How to use gcc instead of g++ on openSUSE

### ISSUE THREAD

**Issue by Nano-Ocelot** [dscharrer/steamwm#4]
openSUSE uses gcc instead of g++ so I'm not sure if there's a workaround. Sorry if this isn't the right place to figure this out, but I don't know where else to go. I tried replacing g++ in line 102 with gcc, but it gave the error 'gcc: error trying to exec 'cc1plus': execvp: No such file or directory.' I'm not sure what to do at this point.

**Comment by dscharrer** [comment]
`g++` is GCC's C++ front end. You might need to install a separate package on some distributions - that will also include the internal `cc1plus` binary.

**Comment by Nano-Ocelot** [comment]
Thank you for the reply. I tried to search for g++ on opensuse to no avail.
I may be out of luck.

**Comment by dscharrer** [comment]
You'll be able to find g++ on any Linux distribution since it is required to build newer versions of GCC itself.

For openSUSE the package seems to be [gcc-c++](https://software.opensuse.org/package/gcc-c++).
